version: '3'

includes:
  nvim: ./nvim/Taskfile.yaml
  fish: ./fish/Taskfile.yaml
  git: ./git/Taskfile.yaml
  homebrew: ./homebrew/Taskfile.yaml
  tmux : ./tmux/Taskfile.yaml

tasks:
  build:
    desc: Build dotfiles
    cmds:
      - task: homebrew:build
      - task: nvim:build
      - task: fish:build
      - task: git:build
      - task: tmux:build